name: Deploy to Production

on:
  push:
    branches:
      - main   # or production branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Build plugin
        run: |
          npm install
          npm run build
          composer install --no-dev --optimize-autoloader

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete
          path: ./   # root of repo
          remote_path: /home/porcelai/emporiosurfaces.com/wp-content/plugins/es-colour-pairings
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}
